[package]
name = "oxc"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]
path = "dummy.rs" # We just need this for Cargo to generate the Cargo.lock

[dependencies]
oxc = { version = "0.140.0", features = [
  "codegen",
  "isolated_declarations",
  "semantic",
  "transformer",
] }
