"Bazel dependencies"

module(
    name = "rules_oxc",
    version = "0.0.0",
)

bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "platforms", version = "1.1.0")

# For the JsInfo provider.
bazel_dep(name = "aspect_rules_js", version = "3.4.0")

# For ts_lib.files_relative_to_package()
bazel_dep(name = "aspect_rules_ts", version = "3.10.0")

bazel_dep(name = "gazelle", version = "0.52.2", dev_dependency = True)
bazel_dep(name = "bazel_skylib_gazelle_plugin", version = "1.4.1", dev_dependency = True)
bazel_dep(name = "aspect_bazel_lib", version = "1.32.1", dev_dependency = True)
bazel_dep(name = "buildifier_prebuilt", version = "6.1.2", dev_dependency = True)

bazel_dep(name = "rules_rust", version = "0.73.0", dev_dependency = True)
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.95.0"],
)
use_repo(
    rust,
    "rust_toolchains",
)

register_toolchains(
    "@rust_toolchains//:all",
)

crate = use_extension(
    "@rules_rust//crate_universe:extension.bzl",
    "crate",
)
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//oxc/private:Cargo.lock",
    manifests = ["//oxc/private:Cargo.toml"],
    supported_platform_triples = [
        "aarch64-unknown-linux-gnu",
        "x86_64-unknown-linux-gnu",
        "aarch64-apple-darwin",
    ],
)
use_repo(crate, "crates")

