load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

rust_binary(
    name = "transpiler",
    srcs = ["transpiler.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "@oxc_crates//:oxc",
    ],
)

rust_test(
    name = "transpiler_test",
    size = "small",
    crate = ":transpiler",
)
