load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")
load("@rules_rust//rust:defs.bzl", "rustfmt_test")

rust_binary(
    name = "transpiler",
    srcs = ["transpiler.rs"],
    visibility = ["//visibility:public"],
    deps = [
        "@oxc_crates//:oxc",
    ],
)

rust_test(
    name = "transpiler_test",
    size = "small",
    crate = ":transpiler",
)

rustfmt_test(
    name = "rustfmt_test",
    targets = [":transpiler"],
)
