load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_binary(
    name = "transpiler",
    srcs = [
        "resolver.rs",
        "transpiler.rs",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@oxc_crates//:oxc",
    ],
)

rust_test(
    name = "transpiler_test",
    size = "small",
    crate = ":transpiler",
)
